config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pets#index'

  resources :pets, only: %i[show new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
# frozen_string_literal: true

class Pet < ApplicationRecord
  def icon_creator
    case species
    when 'dog'
      'dog.png'
    else
      'cat.png'
    end
  end

  enum gender: { male: 0, female: 1 }

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
# frozen_string_literal: true

class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save

    redirect_to pet_path(@pet)
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :gender, :species, :found_on, :age, :available)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pets_helper.rb
# frozen_string_literal: true

module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shelter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pets/index.html.erb
<h1 class="mt-4 mb-4">All Pets 🐻</h1>



<%= link_to "Add a new Pet", new_pet_path, class: "btn btn-success mb-5" %>

<div class="pets-grid">
  <% @pets.each do |pet| %>
  <div class="pet-card hvr-grow ">
    <div>
      <h4><%= pet.name  %></h4>
      <%= image_tag pet.icon_creator %>
    </div>
    <div>
      <h4 class="mt-4">Available:</h4>
      <%= pet.available ? "✓" : "✕" %>
    </div>

    <%= link_to "See more", pet_path(pet.id), class: "btn btn-primary mt-4" %>
  </div>
  <% end %>
</div>

app/views/pets/new.html.erb
<h1 class="mt-5 mb-5">Add a new Pet</h1>

<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :gender, collection: ["f", "m"] %>
  <%= f.input :available %>
  <%= f.input :found_on %>
  <%= f.input :age %>
  <%= f.input :species, collection: ["dog", "cat"] %>

  <%= f.button :submit, class: "btn btn-success" %>
<% end %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<h3><%= @pet.age %></h3>
<h3><%= @pet.species %></h3>
<h3><%= @pet.available %></h3>
<h3><%= @pet.gender %></h3>